SELECT COUNT(*) FROM INSCRITOS;

SELECT SUM(cantidad) FROM INSCRITOS;

SELECT * FROM INSCRITOS WHERE fecha IN (SELECT MIN(fecha) FROM INSCRITOS);

SELECT fecha, SUM(cantidad) FROM INSCRITOS GROUP BY fecha ORDER BY fecha ASC;

SELECT fuente, SUM(cantidad) AS cantidad FROM INSCRITOS GROUP BY fuente ORDER BY cantidad  ASC;

SELECT * FROM INSCRITOS WHERE cantidad in (SELECT MAX(cantidad) FROM INSCRITOS WHERE fuente = 'Blog');

SELECT fecha, AVG(cantidad) FROM INSCRITOS GROUP BY fecha; /* DISCUTIR REDACCION DE LA PREGUNTA*/

SELECT * FROM INSCRITOS WHERE cantidad > 50 ORDER BY fecha;

SELECT fecha, AVG(cantidad) FROM INSCRITOS WHERE fecha >= CAST('2021-01-03' AS date) GROUP BY FECHA ORDER BY fecha;

